language: cpp
dist: bionic
os:
  - linux

jobs:
# AMD64
  include:
    - arch: amd64
      env: CXX=g++-9 CC=gcc-9 GCOV=gcov-9 ARCH=amd64
      before_install:
        - mkdir -p ~/.local/bin
        - eval "PATH=$PATH:~/.local/bin"
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      install:
        - sudo apt-get install python3 -y
        - sudo apt-get install python3-pip -y
        - sudo apt-get install python3-setuptools -y

        - sudo apt-get install g++-9 -y

        - sudo apt-get install pkg-config -y
        - sudo apt-get install zlib1g-dev -y

        - pushd /tmp
        - git clone https://github.com/ninja-build/ninja.git
        - cd ninja
        - python3 ./configure.py --bootstrap
        - cp ninja ~/.local/bin/
        - popd

        - pip3 install --user wheel
        - pip3 install --user meson
        - pip3 install --user codecov

# ARM64
    - arch: arm64
      env: CXX=g++-9 CC=gcc-9 GCOV=gcov-9 ARCH=arm64
      before_install:
        - mkdir -p ~/.local/bin
        - eval "PATH=$PATH:~/.local/bin"
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      install:
        - sudo apt-get install python3 -y
        - sudo apt-get install python3-pip -y
        - sudo apt-get install python3-setuptools -y

        - sudo apt-get install g++-9 -y

        - sudo apt-get install pkg-config -y
        - sudo apt-get install zlib1g-dev -y

        - pushd /tmp
        - git clone https://github.com/ninja-build/ninja.git
        - cd ninja
        - python3 ./configure.py --bootstrap
        - cp ninja ~/.local/bin/
        - popd

        - pip3 install --user wheel
        - pip3 install --user meson
        - pip3 install --user codecov

script:
  - meson -Db_coverage=true -Db_sanitize=address,undefined build
  - ninja -C build
  - ninja -C build test

after_success:
  - cd build
  - codecov --gcov-exec "$GCOV" -e ARCH,CXX
