language: cpp
dist: bionic
os:
  - linux


jobs:
# AMD64
  include:
    - arch: amd64
      env: CXX=g++-9 CC=gcc-9 GCOV=gcov-9 ARCH=amd64
      before_install:
        - mkdir -p ~/.local/bin
        - eval "PATH=$PATH:~/.local/bin"
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      install:
        - sudo apt-get install python3 -y
        - sudo apt-get install python3-pip -y
        - sudo apt-get install python3-setuptools -y

        - sudo apt-get install g++-9 -y

        - sudo apt-get install pkg-config -y
        - sudo apt-get install zlib1g-dev -y

        - pushd /tmp
        - git clone https://github.com/ninja-build/ninja.git
        - cd ninja
        - python3 ./configure.py --bootstrap
        - cp ninja ~/.local/bin/
        - popd

        - pip3 install --user wheel
        - pip3 install --user meson
        - pip3 install --user codecov
    - arch: amd64
      env: CXX=g++-8 CC=gcc-8 GCOV=gcov-8 ARCH=amd64
      before_install:
        - mkdir -p ~/.local/bin
        - eval "PATH=$PATH:~/.local/bin"
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      install:
        - sudo apt-get install python3 -y
        - sudo apt-get install python3-pip -y
        - sudo apt-get install python3-setuptools -y

        - sudo apt-get install g++-8 -y

        - sudo apt-get install pkg-config -y
        - sudo apt-get install zlib1g-dev -y

        - pushd /tmp
        - git clone https://github.com/ninja-build/ninja.git
        - cd ninja
        - python3 ./configure.py --bootstrap
        - cp ninja ~/.local/bin/
        - popd

        - pip3 install --user wheel
        - pip3 install --user meson
        - pip3 install --user codecov
    - arch: amd64
      env: CXX=g++-7 CC=gcc-7 GCOV=gcov-7 ARCH=amd64
      before_install:
        - mkdir -p ~/.local/bin
        - eval "PATH=$PATH:~/.local/bin"
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      install:
        - sudo apt-get install python3 -y
        - sudo apt-get install python3-pip -y
        - sudo apt-get install python3-setuptools -y

        - sudo apt-get install g++-7 -y

        - sudo apt-get install pkg-config -y
        - sudo apt-get install zlib1g-dev -y

        - pushd /tmp
        - git clone https://github.com/ninja-build/ninja.git
        - cd ninja
        - python3 ./configure.py --bootstrap
        - cp ninja ~/.local/bin/
        - popd

        - pip3 install --user wheel
        - pip3 install --user meson
        - pip3 install --user codecov
    - arch: amd64
      env: CXX=clang++-9 CC=clang-9 GCOV='llvm-cov gcov' ARCH=amd64
      before_install:
        - mkdir -p ~/.local/bin
        - eval "PATH=$PATH:~/.local/bin"
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        - sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main" -y
      install:
        - sudo apt-get install python3 -y
        - sudo apt-get install python3-pip -y
        - sudo apt-get install python3-setuptools -y

        - sudo apt-get install g++-9 -y
        - sudo apt-get install clang-9 -y

        - sudo apt-get install pkg-config -y
        - sudo apt-get install zlib1g-dev -y

        - pushd /tmp
        - git clone https://github.com/ninja-build/ninja.git
        - cd ninja
        - python3 ./configure.py --bootstrap
        - cp ninja ~/.local/bin/
        - popd

        - pip3 install --user wheel
        - pip3 install --user meson
        - pip3 install --user codecov
    - arch: amd64
      env: CXX=clang++-8 CC=clang-8 GCOV='llvm-cov gcov' ARCH=amd64
      before_install:
        - mkdir -p ~/.local/bin
        - eval "PATH=$PATH:~/.local/bin"
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        - sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main" -y
      install:
        - sudo apt-get install python3 -y
        - sudo apt-get install python3-pip -y
        - sudo apt-get install python3-setuptools -y

        - sudo apt-get install g++-8 -y
        - sudo apt-get install clang-8 -y

        - sudo apt-get install pkg-config -y
        - sudo apt-get install zlib1g-dev -y

        - pushd /tmp
        - git clone https://github.com/ninja-build/ninja.git
        - cd ninja
        - python3 ./configure.py --bootstrap
        - cp ninja ~/.local/bin/
        - popd

        - pip3 install --user wheel
        - pip3 install --user meson
        - pip3 install --user codecov
    - arch: amd64
      env: CXX=clang++-7 CC=clang-7 GCOV='llvm-cov gcov' ARCH=amd64
      before_install:
        - mkdir -p ~/.local/bin
        - eval "PATH=$PATH:~/.local/bin"
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        - sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-7 main" -y
      install:
        - sudo apt-get install python3 -y
        - sudo apt-get install python3-pip -y
        - sudo apt-get install python3-setuptools -y

        - sudo apt-get install g++-7 -y
        - sudo apt-get install clang-7 -y

        - sudo apt-get install pkg-config -y
        - sudo apt-get install zlib1g-dev -y

        - pushd /tmp
        - git clone https://github.com/ninja-build/ninja.git
        - cd ninja
        - python3 ./configure.py --bootstrap
        - cp ninja ~/.local/bin/
        - popd

        - pip3 install --user wheel
        - pip3 install --user meson
        - pip3 install --user codecov
# ARM64
    - arch: arm64
      env: CXX=g++-9 CC=gcc-9 GCOV=gcov-9 ARCH=arm64
      before_install:
        - mkdir -p ~/.local/bin
        - eval "PATH=$PATH:~/.local/bin"
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      install:
        - sudo apt-get install python3 -y
        - sudo apt-get install python3-pip -y
        - sudo apt-get install python3-setuptools -y

        - sudo apt-get install g++-9 -y

        - sudo apt-get install pkg-config -y
        - sudo apt-get install zlib1g-dev -y

        - pushd /tmp
        - git clone https://github.com/ninja-build/ninja.git
        - cd ninja
        - python3 ./configure.py --bootstrap
        - cp ninja ~/.local/bin/
        - popd

        - pip3 install --user wheel
        - pip3 install --user meson
        - pip3 install --user codecov
    - arch: arm64
      env: CXX=g++-8 CC=gcc-8 GCOV=gcov-8 ARCH=arm64
      before_install:
        - mkdir -p ~/.local/bin
        - eval "PATH=$PATH:~/.local/bin"
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      install:
        - sudo apt-get install python3 -y
        - sudo apt-get install python3-pip -y
        - sudo apt-get install python3-setuptools -y

        - sudo apt-get install g++-8 -y

        - sudo apt-get install pkg-config -y
        - sudo apt-get install zlib1g-dev -y

        - pushd /tmp
        - git clone https://github.com/ninja-build/ninja.git
        - cd ninja
        - python3 ./configure.py --bootstrap
        - cp ninja ~/.local/bin/
        - popd

        - pip3 install --user wheel
        - pip3 install --user meson
        - pip3 install --user codecov
    - arch: arm64
      env: CXX=g++-7 CC=gcc-7 GCOV=gcov-7 ARCH=arm64
      before_install:
        - mkdir -p ~/.local/bin
        - eval "PATH=$PATH:~/.local/bin"
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      install:
        - sudo apt-get install python3 -y
        - sudo apt-get install python3-pip -y
        - sudo apt-get install python3-setuptools -y

        - sudo apt-get install g++-7 -y

        - sudo apt-get install pkg-config -y
        - sudo apt-get install zlib1g-dev -y

        - pushd /tmp
        - git clone https://github.com/ninja-build/ninja.git
        - cd ninja
        - python3 ./configure.py --bootstrap
        - cp ninja ~/.local/bin/
        - popd

        - pip3 install --user wheel
        - pip3 install --user meson
        - pip3 install --user codecov

script:
  - meson -Db_coverage=true -Db_sanitize=address,undefined build
  - ninja -C build
  - ninja -C build test

after_success:
  - cd build
  - codecov --gcov-exec "$GCOV" -e ARCH,CXX
